name: my_kurir_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.2.3
  zikzak_inappwebview: ^2.4.8
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^14.0.1
  shared_preferences: ^2.5.3
  firebase_core: ^3.14.0
  cloud_firestore: ^5.6.9
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  intl: ^0.20.2
  firebase_messaging: ^15.2.7
  firebase_auth: ^5.6.0
  flutter_local_notifications: ^19.3.0
  flutter_launcher_icons: ^0.14.4
  flagsmith: ^6.0.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ic_launcher.png"
  adaptive_icon_foreground: "assets/ic_launcher.png"
  adaptive_icon_background: "3121D36"
